// ============================================================================
// Markdown Report Generator
// Generates human-readable test reports with summary tables
// ============================================================================

import * as fs from "fs";
import * as path from "path";
import type {
  TestSuiteResult,
  FlashSaleResult,
  ChaosTestResult,
  ValidationResult,
  ValidationCheck,
  ReportOptions,
} from "../types";

const DEFAULT_OUTPUT_PATH = "./test-report.md";

export function generateMarkdownReport(
  result: TestSuiteResult,
  options: Partial<ReportOptions> = {}
): string {
  const outputPath = options.outputPath || DEFAULT_OUTPUT_PATH;
  const includeRawData = options.includeRawData ?? false;
  const verbose = options.verbose ?? false;

  const lines: string[] = [];

  // Header
  lines.push(`# Test Report - ${formatDate(result.startTime)}`);
  lines.push("");
  lines.push(`**Run ID:** \`${result.runId}\``);
  lines.push(`**Duration:** ${formatDuration(result.durationMs)}`);
  lines.push(
    `**Status:** ${result.overallSuccess ? "✅ PASSED" : "❌ FAILED"}`
  );
  lines.push("");

  // Summary Section
  lines.push("## Summary");
  lines.push("");
  lines.push("| Metric | Value |");
  lines.push("|--------|-------|");
  lines.push(`| Start Time | ${formatDate(result.startTime)} |`);
  lines.push(`| End Time | ${formatDate(result.endTime)} |`);
  lines.push(`| Total Duration | ${formatDuration(result.durationMs)} |`);
  lines.push(
    `| Overall Result | ${result.overallSuccess ? "PASSED" : "FAILED"} |`
  );
  lines.push("");

  // Quick Stats
  lines.push("### Quick Stats");
  lines.push("");

  const quickStats: string[][] = [];
  if (result.scenarios.flashSale) {
    quickStats.push([
      "Flash Sale Orders",
      String(result.scenarios.flashSale.metrics.ordersCreated),
    ]);
    quickStats.push([
      "Flash Sale Webhooks",
      String(result.scenarios.flashSale.metrics.webhooksSent),
    ]);
  }
  if (result.scenarios.chaosTest) {
    quickStats.push([
      "Chaos Test Events",
      String(result.scenarios.chaosTest.metrics.totalEventsGenerated),
    ]);
    quickStats.push([
      "Timestamp Valid",
      result.scenarios.chaosTest.metrics.timestampMatchValid ? "Yes" : "No",
    ]);
  }
  quickStats.push([
    "Validations Passed",
    `${result.validation.passCount}/${result.validation.checks.length}`,
  ]);

  if (quickStats.length > 0) {
    lines.push("| Metric | Value |");
    lines.push("|--------|-------|");
    for (const [metric, value] of quickStats) {
      lines.push(`| ${metric} | ${value} |`);
    }
    lines.push("");
  }

  // Flash Sale Results
  if (result.scenarios.flashSale) {
    lines.push(...generateFlashSaleSection(result.scenarios.flashSale, verbose));
  }

  // Chaos Test Results
  if (result.scenarios.chaosTest) {
    lines.push(...generateChaosTestSection(result.scenarios.chaosTest, verbose));
  }

  // Validation Results
  lines.push(...generateValidationSection(result.validation, verbose));

  // Errors and Warnings
  lines.push(...generateErrorsSection(result));

  // Configuration
  if (verbose) {
    lines.push("## Configuration");
    lines.push("");
    lines.push("```json");
    lines.push(JSON.stringify(result.config, null, 2));
    lines.push("```");
    lines.push("");
  }

  // Raw Data (if requested)
  if (includeRawData) {
    lines.push("## Raw Data");
    lines.push("");
    lines.push("<details>");
    lines.push("<summary>Click to expand raw result data</summary>");
    lines.push("");
    lines.push("```json");
    lines.push(JSON.stringify(result, null, 2));
    lines.push("```");
    lines.push("");
    lines.push("</details>");
    lines.push("");
  }

  // Footer
  lines.push("---");
  lines.push("");
  lines.push(
    `*Generated by Fincart Test Suite at ${new Date().toISOString()}*`
  );

  const content = lines.join("\n");

  // Write to file
  const fullPath = path.resolve(outputPath);
  fs.writeFileSync(fullPath, content, "utf-8");
  console.log(`[Reporter] Report written to: ${fullPath}`);

  return content;
}

// ============================================================================
// Section Generators
// ============================================================================

function generateFlashSaleSection(
  result: FlashSaleResult,
  verbose: boolean
): string[] {
  const lines: string[] = [];

  lines.push("## Flash Sale Results");
  lines.push("");
  lines.push(
    `**Status:** ${result.success ? "✅ Passed" : "❌ Failed"} | ` +
      `**Duration:** ${formatDuration(result.durationMs)}`
  );
  lines.push("");

  // Metrics Table
  lines.push("### Metrics");
  lines.push("");
  lines.push("| Metric | Value |");
  lines.push("|--------|-------|");
  lines.push(
    `| Orders Attempted | ${result.metrics.totalOrdersAttempted.toLocaleString()} |`
  );
  lines.push(
    `| Orders Created | ${result.metrics.ordersCreated.toLocaleString()} |`
  );
  lines.push(
    `| Webhooks Sent | ${result.metrics.webhooksSent.toLocaleString()} |`
  );
  lines.push(
    `| Courier Events Sent | ${result.metrics.courierEventsSent.toLocaleString()} |`
  );
  lines.push(
    `| Duplicates Generated | ${result.metrics.duplicatesGenerated.toLocaleString()} |`
  );
  lines.push(
    `| Duplicates Handled | ${result.metrics.duplicatesHandled.toLocaleString()} |`
  );
  lines.push(`| Avg Processing Time | ${result.metrics.avgProcessingTimeMs}ms |`);
  lines.push(
    `| Peak Orders/Second | ${result.metrics.peakOrdersPerSecond.toLocaleString()} |`
  );
  lines.push("");

  // Success Rate Calculation
  const successRate =
    result.metrics.totalOrdersAttempted > 0
      ? (
          (result.metrics.ordersCreated / result.metrics.totalOrdersAttempted) *
          100
        ).toFixed(2)
      : "N/A";
  lines.push(`**Success Rate:** ${successRate}%`);
  lines.push("");

  // Errors
  if (result.errors.length > 0) {
    lines.push("### Errors");
    lines.push("");
    for (const error of result.errors.slice(0, 10)) {
      lines.push(`- ${error}`);
    }
    if (result.errors.length > 10) {
      lines.push(`- ... and ${result.errors.length - 10} more errors`);
    }
    lines.push("");
  }

  // Warnings
  if (result.warnings.length > 0) {
    lines.push("### Warnings");
    lines.push("");
    for (const warning of result.warnings) {
      lines.push(`- ⚠️ ${warning}`);
    }
    lines.push("");
  }

  return lines;
}

function generateChaosTestSection(
  result: ChaosTestResult,
  verbose: boolean
): string[] {
  const lines: string[] = [];

  lines.push("## Chaos Test Results");
  lines.push("");
  lines.push(
    `**Status:** ${result.success ? "✅ Passed" : "❌ Failed"} | ` +
      `**Duration:** ${formatDuration(result.durationMs)}`
  );
  lines.push("");

  lines.push(`**Order ID:** \`${result.metrics.orderId}\``);
  lines.push("");

  // Metrics Table
  lines.push("### Metrics");
  lines.push("");
  lines.push("| Metric | Value |");
  lines.push("|--------|-------|");
  lines.push(
    `| Total Events Generated | ${result.metrics.totalEventsGenerated} |`
  );
  lines.push(`| Shopify Events | ${result.metrics.shopifyEvents} |`);
  lines.push(`| Courier Events | ${result.metrics.courierEvents} |`);
  lines.push(`| Duplicates Generated | ${result.metrics.duplicatesGenerated} |`);
  lines.push(`| Inbox Items Processed | ${result.metrics.inboxItemsProcessed} |`);
  lines.push("");

  // Timestamp Validation
  lines.push("### Timestamp Validation");
  lines.push("");
  lines.push(
    `| Check | Expected | Actual | Status |`
  );
  lines.push("|-------|----------|--------|--------|");
  lines.push(
    `| lastEventTs | ${result.metrics.expectedMaxTimestamp} | ${result.metrics.actualLastEventTs} | ${result.metrics.timestampMatchValid ? "✅" : "❌"} |`
  );
  lines.push("");

  // Shipment Check
  lines.push("### Shipment Status");
  lines.push("");
  lines.push(
    `Shipment Exists: ${result.metrics.shipmentExists ? "✅ Yes" : "❌ No"}`
  );
  lines.push("");

  // Errors
  if (result.errors.length > 0) {
    lines.push("### Errors");
    lines.push("");
    for (const error of result.errors) {
      lines.push(`- ${error}`);
    }
    lines.push("");
  }

  // Warnings
  if (result.warnings.length > 0) {
    lines.push("### Warnings");
    lines.push("");
    for (const warning of result.warnings) {
      lines.push(`- ⚠️ ${warning}`);
    }
    lines.push("");
  }

  return lines;
}

function generateValidationSection(
  validation: ValidationResult,
  verbose: boolean
): string[] {
  const lines: string[] = [];

  lines.push("## Validation Results");
  lines.push("");

  // Summary
  const statusEmoji = {
    pass: "✅",
    fail: "❌",
    warning: "⚠️",
    skipped: "⏭️",
  };

  lines.push(
    `**Overall Status:** ${statusEmoji[validation.overallStatus]} ${validation.overallStatus.toUpperCase()}`
  );
  lines.push("");
  lines.push(
    `| Passed | Failed | Warnings | Skipped |`
  );
  lines.push("|--------|--------|----------|---------|");
  lines.push(
    `| ${validation.passCount} | ${validation.failCount} | ${validation.warningCount} | ${validation.skippedCount} |`
  );
  lines.push("");

  // Individual Checks
  lines.push("### Validation Checks");
  lines.push("");
  lines.push("| Check | Status | Details |");
  lines.push("|-------|--------|---------|");

  for (const check of validation.checks) {
    const emoji = statusEmoji[check.status];
    const details = truncate(check.details, 60);
    lines.push(`| ${check.name} | ${emoji} ${check.status} | ${details} |`);
  }
  lines.push("");

  // Detailed check information (if verbose)
  if (verbose) {
    lines.push("### Detailed Check Information");
    lines.push("");

    for (const check of validation.checks) {
      lines.push(`#### ${check.name}`);
      lines.push("");
      lines.push(`**Description:** ${check.description}`);
      lines.push("");
      lines.push(`**Status:** ${statusEmoji[check.status]} ${check.status}`);
      lines.push("");
      lines.push(`**Details:** ${check.details}`);
      lines.push("");

      if (check.data && Object.keys(check.data).length > 0) {
        lines.push("**Data:**");
        lines.push("```json");
        lines.push(JSON.stringify(check.data, null, 2));
        lines.push("```");
        lines.push("");
      }
    }
  }

  return lines;
}

function generateErrorsSection(result: TestSuiteResult): string[] {
  const lines: string[] = [];

  const allErrors: string[] = [];
  const allWarnings: string[] = [];

  if (result.scenarios.flashSale) {
    allErrors.push(...result.scenarios.flashSale.errors);
    allWarnings.push(...result.scenarios.flashSale.warnings);
  }
  if (result.scenarios.chaosTest) {
    allErrors.push(...result.scenarios.chaosTest.errors);
    allWarnings.push(...result.scenarios.chaosTest.warnings);
  }

  if (allErrors.length > 0 || allWarnings.length > 0) {
    lines.push("## Issues Summary");
    lines.push("");

    if (allErrors.length > 0) {
      lines.push(`### Errors (${allErrors.length})`);
      lines.push("");
      for (const error of allErrors.slice(0, 20)) {
        lines.push(`- ❌ ${error}`);
      }
      if (allErrors.length > 20) {
        lines.push(`- ... and ${allErrors.length - 20} more errors`);
      }
      lines.push("");
    }

    if (allWarnings.length > 0) {
      lines.push(`### Warnings (${allWarnings.length})`);
      lines.push("");
      for (const warning of allWarnings) {
        lines.push(`- ⚠️ ${warning}`);
      }
      lines.push("");
    }
  }

  // Recommendations
  lines.push("## Recommendations");
  lines.push("");

  if (result.overallSuccess) {
    lines.push("✅ All tests passed successfully. No immediate action required.");
  } else {
    lines.push("Based on the test results, consider the following:");
    lines.push("");

    if (result.validation.failCount > 0) {
      lines.push(
        "- Review failed validation checks for data consistency issues"
      );
    }

    const flashSale = result.scenarios.flashSale;
    if (flashSale && flashSale.metrics.ordersCreated < flashSale.metrics.totalOrdersAttempted * 0.95) {
      lines.push(
        "- Investigate order creation failures - consider increasing timeout or batch size"
      );
    }

    const chaosTest = result.scenarios.chaosTest;
    if (chaosTest && !chaosTest.metrics.timestampMatchValid) {
      lines.push(
        "- Review event ordering logic - timestamp reconciliation may have issues"
      );
    }

    if (result.validation.warningCount > 0) {
      lines.push("- Address warnings to prevent potential future issues");
    }
  }
  lines.push("");

  return lines;
}

// ============================================================================
// Utility Functions
// ============================================================================

function formatDate(date: Date): string {
  return date.toISOString().replace("T", " ").split(".")[0] + " UTC";
}

function formatDuration(ms: number): string {
  if (ms < 1000) {
    return `${ms}ms`;
  }
  if (ms < 60000) {
    return `${(ms / 1000).toFixed(2)}s`;
  }
  const minutes = Math.floor(ms / 60000);
  const seconds = ((ms % 60000) / 1000).toFixed(0);
  return `${minutes}m ${seconds}s`;
}

function truncate(str: string, maxLength: number): string {
  if (str.length <= maxLength) {
    return str;
  }
  return str.substring(0, maxLength - 3) + "...";
}

// ============================================================================
// Export additional utilities
// ============================================================================

export function printSummaryToConsole(result: TestSuiteResult): void {
  console.log("\n" + "=".repeat(60));
  console.log("TEST SUITE SUMMARY");
  console.log("=".repeat(60));
  console.log(`Run ID: ${result.runId}`);
  console.log(`Duration: ${formatDuration(result.durationMs)}`);
  console.log(`Status: ${result.overallSuccess ? "✅ PASSED" : "❌ FAILED"}`);
  console.log("");

  if (result.scenarios.flashSale) {
    const fs = result.scenarios.flashSale;
    console.log(`Flash Sale: ${fs.success ? "✅" : "❌"} (${fs.metrics.ordersCreated}/${fs.metrics.totalOrdersAttempted} orders)`);
  }

  if (result.scenarios.chaosTest) {
    const ct = result.scenarios.chaosTest;
    console.log(`Chaos Test: ${ct.success ? "✅" : "❌"} (${ct.metrics.totalEventsGenerated} events, timestamp valid: ${ct.metrics.timestampMatchValid})`);
  }

  console.log("");
  console.log(`Validations: ${result.validation.passCount}/${result.validation.checks.length} passed`);

  if (result.validation.failCount > 0) {
    console.log(`  - ${result.validation.failCount} failed`);
  }
  if (result.validation.warningCount > 0) {
    console.log(`  - ${result.validation.warningCount} warnings`);
  }

  console.log("=".repeat(60) + "\n");
}
